### ISSUE TITLE
No such file config_changes.txt

### ISSUE THREAD

**Issue by rewingchow1** [cmu-snap/pigasus#4]
When running command "make -j $(nproc) install", I get the following warning. When line 110 is commented out frompigasus/software/build_pigasus/doc/cmake_install.cmake it works fine. Is there something I missed in the prior steps for not having config_changes.txt?

![Screen Shot 2021-06-30 at 1 25 43 AM](https://user-images.githubusercontent.com/71918289/123910839-008cce80-d949-11eb-8916-bd8a19c64b46.png)

**Comment by hsadok** [comment]
Hi Randy,

Thank you for reporting this. This file is part of the Snort docs and should not affect Pigasus' behavior. But you should not be having this issue.

Are you using Ubuntu 18.04? I wonder if this is caused by not having ruby properly installed in your system. Would you mind trying to install ruby and repeating the steps to see if the problem goes away?

**Comment by rewingchow1** [comment]
Hi Hugo,

I am using Ubuntu 16.04 on one system and Ubuntu 20.04 on the other system. This was tried on both systems. I do not have ruby installed on my system and this might be the issue. Will try again.

Thanks,
Randy
![Screen Shot 2021-07-06 at 2 01 44 PM](https://user-images.githubusercontent.com/71918289/124646488-b3d25780-de62-11eb-9021-6a2781f092da.png)
![Screen Shot 2021-07-06 at 2 01 55 PM](https://user-images.githubusercontent.com/71918289/124646499-b92fa200-de62-11eb-99aa-bdd472a0de3a.png)

**Comment by rewingchow1** [comment]
Installing Ruby fixed the issue on both systems. Thanks Hugo.
